/*
 * Copyright (c) 2026 Vitor Pamplona
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the
 * Software, and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN
 * AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
 * WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
package com.vitorpamplona.neo4j.eventstore.engine.vocab

import java.io.File
import kotlin.test.Test
import kotlin.test.assertEquals

/**
 * `docs/relations.md` is the relation catalog read off the code: every relationship type and
 * what it may point at ([Relation.targets]). Written, never hand-edited, so the docs cannot say
 * one thing while the builder enforces another. After changing a relation, regenerate it:
 * `UPDATE_DOCS=1 ./gradlew :engine:test --tests '*RelationCatalogTest'`.
 */
class RelationCatalogTest {
    @Test
    fun theCatalogMatchesTheCode() {
        val file = listOf(File("../docs/relations.md"), File("docs/relations.md")).first { it.parentFile.isDirectory }
        val expected = render()
        if (System.getenv("UPDATE_DOCS") == "1") file.writeText(expected)
        assertEquals(
            expected,
            if (file.exists()) file.readText() else "",
            "docs/relations.md is stale: regenerate it (see this test's KDoc)",
        )
    }

    private fun render(): String {
        val nodes = NodeTarget.entries
        val out = StringBuilder()
        out.append("# Relation catalog\n\n")
        out.append("<!-- Generated by RelationCatalogTest from vocab/Relation.kt. Do not edit by hand. -->\n\n")
        out.append("Every relationship type the projection writes, and what it may point at. The builder refuses\n")
        out.append("any other target, so this table is what a query can rely on. What each relation MEANS, and\n")
        out.append("which kinds state it, is in [vocabulary.md](vocabulary.md).\n\n")
        out.append("Targets: `event` (an `:Event`), `address` (an `:Address`), `user` (a `:User`), or a value type,\n")
        out.append("which is a `:Tag` node keyed `<type>:<value>`.\n\n")
        out.append("| Relation | Targets |\n|---|---|\n")
        for (relation in Relation.ALL.sortedBy { it.name }) {
            val targets =
                nodes.filter { it in relation.targets } + ValueType.entries.filter { it in relation.targets }
            out.append("| `").append(relation.name).append("` | ")
            out.append(targets.joinToString(", ") { "`" + it.code + "`" })
            out.append(" |\n")
        }
        out.append("\n## Value types\n\n| Type | What it is |\n|---|---|\n")
        for (type in ValueType.entries) {
            out
                .append("| `")
                .append(type.code)
                .append("` | ")
                .append(type.description)
                .append(" |\n")
        }
        return out.toString()
    }
}
